using System;
using Newtonsoft.Json;

namespace CloudFlareSharp.Api.V2.RealtimeKitApi.MeetingsModels
{
    public class AddParticipantsResponse
    {
        /// <summary>
        /// ID of the participant.
        /// 参与者ID
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; }

        /// <summary>
        /// Name of the participant.
        /// 参与者姓名
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// URL to a picture of the participant.
        /// 参与者头像URL
        /// </summary>
        [JsonProperty("picture")]
        public string Picture { get; set; }

        /// <summary>
        /// A unique participant ID generated by the client.
        /// 由客户端生成的唯一参与者ID
        /// </summary>
        [JsonProperty("custom_participant_id")]
        public string CustomParticipantId { get; set; }

        /// <summary>
        /// Preset applied to the participant.
        /// 应用于参与者的预设
        /// </summary>
        [JsonProperty("preset_id")]
        public string PresetId { get; set; }

        /// <summary>
        /// When this object was created. The time is returned in ISO format.
        /// 创建此对象的时间，以ISO格式返回
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// When this object was updated. The time is returned in ISO format.
        /// 更新此对象的时间，以ISO格式返回
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// The participant's auth token that can be used for joining a meeting from the client side.
        /// 参与者的身份验证令牌，可用于从客户端加入会议
        /// </summary>
        [JsonProperty("token")]
        public string Token { get; set; }
        [JsonProperty("sip_enabled")]
        public bool SipEnabled { get; set; }
    }
}